In [2]:
import arff, numpy as np

In [7]:
dataset = arff.load(open('/home/xueyou/data/test/emotions.arff'))

In [8]:
data = np.array(dataset['data'], dtype=np.float)

In [9]:
data.shape

(593, 78)

In [10]:
# 把数据集划为测试集和训练集
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data[:, :-6], data[:, -6:], test_size=0.33, random_state=42)

In [13]:
y_train

array([[ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  1.,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [24]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

# 分类器使用1对多，SVM用linear kernel
clf1 = OneVsRestClassifier(LogisticRegression(), n_jobs=-1)

In [25]:
# 训练
clf1.fit(X_train, y_train)

OneVsRestClassifier(estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
          n_jobs=-1)

In [26]:
# 输出预测的标签结果
predict_class = clf1.predict(X_test)

In [27]:
predict_class

array([[0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ..., 
       [0, 0, 1, 1, 1, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0]])

In [28]:
y_test

array([[ 0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  1.],
       ..., 
       [ 0.,  0.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  1.],
       [ 0.,  0.,  1.,  1.,  1.,  0.]])

In [29]:
np.mean(predict_class == y_test)

0.79931972789115646